name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get commit history since last tag
        id: commit_history
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 ${GITHUB_REF#refs/tags/}^ 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"* %s (%h)" --no-merges)
          else
            COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"* %s (%h)" --no-merges)
          fi
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pre-release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: build/libs/*.jar
          body: |
            ## Changes in this release:
            ${{ steps.commit_history.outputs.commits }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Filename for Release
        id: prepare_filename
        run: |
          TAG_NAME=${{ github.ref_name }}
          VERSION=${TAG_NAME#v}
          BASE_NAME="create_originium_industry"
          FILE_NAME="${BASE_NAME}-${VERSION}.jar"
          FILE_PATH="build/libs/${FILE_NAME}"
          echo "filepath=${FILE_PATH}" >> $GITHUB_OUTPUT
          echo "Using file path: ${FILE_PATH}"

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: NUmfxgJQ
          version: ${{ github.ref_name }}
          channel: ${{ contains(github.ref_name, '-dev') && 'alpha' || 'release' }}
          changelog: |
            ## Changes in this release:
            ${{ steps.commit_history.outputs.commits }}
          loaders: |-
            neoforge
          game-versions: |-
            1.21.1
          dependencies: |-
            [{
              "project_id": "LNytGWDc",
              "dependency_type": "required"
            }]
          files: ${{ steps.prepare_filename.outputs.filepath }}

      - name: Publish to Curseforge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 1247319
          game_endpoint: minecraft
          relations: "create:requiredDependency"
          game_versions: "Minecraft 1.21:1.21.1,Java 21,NeoForge,Client,Server"
          release_type: ${{ contains(github.ref_name, '-dev') && 'alpha' || 'release' }}
          changelog_type: markdown
          changelog: |
            ## Changes in this release:
            ${{ steps.commit_history.outputs.commits }}
          file_path: ${{ steps.prepare_filename.outputs.filepath }}